#!/bin/sh
make -C $PWD/../../../../kernel \
         ARCH=arm \
         LOCALVERSION= \
         M=$PWD \
         CROSS_COMPILE=arm-linux-gnueabihf- \
         modules
#make -C $PWD/../../../../kernel \
#         ARCH=arm \
#         LOCALVERSION= \
#         M=$PWD \
#         CROSS_COMPILE=arm-linux-gnueabihf- \
#         INSTALL_MOD_PATH=$PWD \
#         modules_install
         #INSTALL_MOD_PATH=$PWD/../../../../rootfs_overlay \

