#!/bin/sh
make -C /home/opa/embedded/fpga/xilinx/zynq/proj/template/kernel \
         ARCH=arm \
         LOCALVERSION= \
         M=$PWD \
         CROSS_COMPILE=arm-linux-gnueabihf- \
         modules
make -C /home/opa/embedded/fpga/xilinx/zynq/proj/template/kernel \
         ARCH=arm \
         LOCALVERSION= \
         M=$PWD \
         CROSS_COMPILE=arm-linux-gnueabihf- \
         INSTALL_MOD_PATH=/home/opa/embedded/fpga/xilinx/zynq/proj/template/rootfs_overlay \
         modules_install

