#!/bin/sh

export $(grep -v '^#' .env | xargs -d '\n')
#read and set path enviroments
#grep -v '^#' .env

mkdir -p buildroot
mkdir -p apps

mkdir -p $BUILDROOT/buildroot
echo $BUILDROOT
make -C $BUILDROOT \
        O=$PWD/buildroot \
        ARCH=arm \
        BR2_EXTERNAL=$PWD/br2_external/apps:$PWD/br2_external/kernel_modules \
        nconfig
        #BR2_EXTERNAL=$PWD/apps \
        #BR2_EXTERNAL_KERNEL_MODULE=$PWD/kernel_modules \
#make -C $BUILDROOT \
#         O=$PWD/buildroot \
#         ARCH=arm \
#         BR2_EXTERNAL=$PWD/apps \
#         busybox-menuconfig
